### ISSUE TITLE
Path changed for ndk bundle?

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [bbqsrc/cargo-ndk#10]
I just reinstalled Android studio and the entire sdk last night, and the option for the ndk install seems to have changed from previous versions.

When I was running "cargo ndk" it was failing as it was looking for "ndk-bundle" in the android sdk directory.

My newly installed ndk was at ~/Library/Android/sdk/ndk/$version_number/ instead of sdk/ndk-bundle

To workaround it, I softlinked one to the other and then "cargo ndk" worked just fine.

FYI

**Comment by bbqsrc** [comment]
This is fixed in current git main version. Feel free to test it and let me know how it runs for you.
