### ISSUE TITLE
Add rpath or link-args flag

### ISSUE THREAD

**Issue by clitic** [bbqsrc/cargo-ndk#103]
I have some c++ code, to build my app for android it needs to be linked to `libc++_shared.so`. To load this library I need to properly set rpath in my main app. Currently, I do this by using `RUSTFLAGS=-C link-arg=-Wl,--rpath=/data/data/com...`. If you can add something like `--rpath` or `--link-args` flag it would be great.

**Comment by bbqsrc** [comment]
`cargo-ndk` is just a thin wrapper around Cargo. You can simply use RUSTFLAGS as you already do.

**Comment by clitic** [comment]
@bbqsrc Thanks for your response.
