### ISSUE TITLE
Cargo ndk ignores --manifest-path

### ISSUE THREAD

**Issue by ubamrein** [bbqsrc/cargo-ndk#11]
Hi there :)

First of all thanks for this nice helper!

Since the last update we face a problem, since we are building the cargo project via Gradle from within Android-Studio and use the cargo "--manifest-path" option to specify the location of the Rust project. Since the CLI now uses `cargo-metadata` and sets the manifest path explicitly on the line below, we face an error.

https://github.com/bbqsrc/cargo-ndk/blob/06aff0bbca1851322bab4b711786be3a3b456e2d/src/cli.rs#L111

Currently, we, as a workaround, change working directory, but I would suggest checking and using the `--manifest-path` option.

`The CLI should check if the cargo option `--manifest-path` is set, and use it for all calls to cargo.`

**Comment by bbqsrc** [comment]
I wasn't aware anybody had gotten this to work with gradle. Mind sharing how that's being done?

I will look into that. Of course, in the mean time, you can always specify `cargo install cargo-ndk --vers 1.0.0` in the mean time. Happy to accept a pull request as well. 😄

**Comment by ubamrein** [comment]
Haha :D 

Yeah I know that one, but I really like the new targets, as it is easier for Android-Devs to understand what is happening :) 

Sure no problem!

The NDK resolution on OSX wasn't working (saw a commit fixing that) this is why we set the NDK explicitly in the beginning. I double check later on if it is still needed :) Also we now could leverage the `output-dir` of the CLI as well.

From Gradle we essentially just execute a shell script (so currently it is probably not directly compatible with windows, though one could provide a Batch/Powershell script and a Shell-Script). We get  the compile-sdk version from the main Gradle file via a variable.

```bash
#!/bin/bash
# Script to build the Rust library for Android and put the output in the correct location
#
# This script takes two parameters:
# $1: the compileSdkVersion to build for
# $2: the base path to the framework repository
# Fail this script when any of its commands fail
set -e
source ~/.cargo/env
# we need cargo ndk
cargo install cargo-ndk --version ^2
# Path to repository location
REPO=$2
JNI_LIBS=$REPO/android/src/main/jniLibs
RUST_ROOT=$REPO/rust/fido-android
echo "JNI_LIBS: $JNI_LIBS"
echo "RUST_ROOT: $RUST_ROOT"
# Check if NDK exists
if [ ! -d "$ANDROID_NDK_HOME" ];
then
  echo "No ANDROID_NDK_HOME was found, trying to detect it from ANDROID_HOME!"
  export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
  echo "Android home: $ANDROID_HOME"
  echo "Android NDK home: $ANDROID_NDK_HOME"
fi
[[ $1 =~  [^0-9]+([0-9]+) ]]
PLATFORM=${BASH_REMATCH[1]}
echo "Building Rust library with cargo for platform $PLATFORM ($1)..."
# Add additional architectures here
WD=$(pwd)
cd $RUST_ROOT
cargo ndk --platform $PLATFORM --target arm64-v8a build --manifest-path $RUST_ROOT/Cargo.toml --release
cargo ndk --platform $PLATFORM --target armeabi-v7a build --manifest-path $RUST_ROOT/Cargo.toml --release
cargo ndk --platform $PLATFORM --target x86_64 build --manifest-path $RUST_ROOT/Cargo.toml --release
cargo ndk --platform $PLATFORM --target x86 build --manifest-path $RUST_ROOT/Cargo.toml --release
cd $WD
echo "Removing old jniLibs and adding the freshly built ones..."
rm -rf "$JNI_LIBS"
mkdir "$JNI_LIBS"
# Add additional architectures here
mkdir "$JNI_LIBS/arm64-v8a"
mkdir "$JNI_LIBS/armeabi-v7a"
mkdir "$JNI_LIBS/x86_64"
mkdir "$JNI_LIBS/x86"
cp "$RUST_ROOT/target/aarch64-linux-android/release/lib.so" "$JNI_LIBS/arm64-v8a/lib.so"
cp "$RUST_ROOT/target/armv7-linux-androideabi/release/lib.so" "$JNI_LIBS/armeabi-v7a/lib.so"
cp "$RUST_ROOT/target/x86_64-linux-android/release/lib.so" "$JNI_LIBS/x86_64/lib.so"
cp "$RUST_ROOT/target/i686-linux-android/release/lib.so" "$JNI_LIBS/x86/lib.so"
echo "Done!"
```

```gradle
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
	compileSdkVersion rootProject.ext.compileSdkVersion
	preBuild.doFirst {
		println("Building Native Rust Library")

		def proc = "bash $rootDir/build_android.sh $compileSdkVersion $rootDir".execute()
		proc.waitForProcessOutput(System.out, System.err)
	}

	defaultConfig {
		minSdkVersion rootProject.ext.minSdkVersion
		targetSdkVersion rootProject.ext.targetSdkVersion
		versionCode 1
		versionName "1.0"
	}

	compileOptions {
		sourceCompatibility 1.8
		targetCompatibility 1.8
	}

	kotlinOptions {
		jvmTarget = "1.8"
	}
}

dependencies {
	implementation 'androidx.annotation:annotation:1.1.0'
	implementation 'ch.ubique.android:utils-kt:1.5'
}

clean.doFirst {
	def proc = "cargo clean --manifest-path $rootDir/Cargo.toml".execute()
	proc.waitForProcessOutput(System.out, System.err)
}
```

I will try to make a pull request later this day :)

**Comment by bbqsrc** [comment]
I did not know that this could work in gradle, haha. Nice.

One suggestion for the PR: we'd still need to pass the manifest path flag to the underlying cargo call, so once the path has been parsed by gumdrop, also add it to the `cargo_args` so cargo gets it as well.

**Comment by ubamrein** [comment]
I did not add it to the `cargo_args`, as they are a `Vec<String>` and `PathBuf` does not need to be valid utf-8 (https://doc.rust-lang.org/std/path/struct.Path.html#method.to_str) but rather leave it as `PathBuf` and add it as a argument to the run call. I hope that is ok :)

**Comment by bbqsrc** [comment]
Yup this solution is better.
