### ISSUE TITLE
Add cdylib automically via `--crate-type`

### ISSUE THREAD

**Issue by jbis9051** [bbqsrc/cargo-ndk#111]
Android requires the `Cargo.toml` to include

```
[lib]
crate-type = ["staticlib", "cdylib"]
```

This is problematic for users who also want to build for iOS. See https://github.com/rust-lang/cargo/issues/4881.

Could this crate leverage https://github.com/rust-lang/cargo/issues/10083 to add `cdylib` to all the `rustc` calls instead of requiring it to be specified in `Cargo.toml`?

**Comment by bbqsrc** [comment]
`cargo-ndk` is just a thin wrapper around `cargo`.

Try `cargo ndk rustc --crate-type=cdylib`.
