### ISSUE TITLE
error[E0308]: mismatched types 

### ISSUE THREAD

**Issue by randrievskiy** [bbqsrc/cargo-ndk#117]
One more issue from me.
When building with 
```
cargo ndk -o ../app/src/main/jniLibs -t aarch64-linux-android build --release
``` 
we've encountered an error:
```
error[E0308]: mismatched types
expected raw pointer `*const u8`
found raw pointer `*const i8`
``` 
but building it with `cargo build` works.

Here is the code:
```
hb_language_from_string(
   language.as_ptr() as *const i8
)

extern "C" {
  pub fn hb_language_from_string(
     str_: *const ::std::os::raw::c_char
  ) -> hb_language_t;
}
``` 

Host machine is MacOS/M1

**Comment by bbqsrc** [comment]
You've provided an error with almost no context, but it is quite clear the issue is a `u8` is not an `i8`. This is not a bug with cargo-ndk.

If you're using C types in Rust, use the `libc` crate for platform independence.
