### ISSUE TITLE
Changes for 3.3 release haven't been pushed to main

### ISSUE THREAD

**Issue by rib** [bbqsrc/cargo-ndk#119]
I see that there's a 3.3 release of `cargo ndk` on crates.io and there's a v3.3 tag https://github.com/bbqsrc/cargo-ndk/releases/tag/v3.3.0 which shows some changes to formatting and handling of `-v/-vv` but I don't currently see these corresponding changes on `main` which is a bit surprising.

**Comment by bbqsrc** [comment]
I'm just dumb and currently on bad internet. It apparently lagged out during the push.
