### ISSUE TITLE
A library produces .sos with undefined symbols

### ISSUE THREAD

**Issue by mavavilj** [bbqsrc/cargo-ndk#124]
I am using cargo-ndk for the first time, and I have not used Rust before.

I tried building https://github.com/Sytronik/pyin-rs with it.

The resulting .sos list the symbols as undefined when viewed with llvm-nm of the respective NDK.

Is the crate built faultily for the purposes of cargo-ndk?

**Comment by bbqsrc** [comment]
This is not a bug with cargo-ndk.

**Comment by mavavilj** [comment]
Thank you.

Okay so the crate is incompatible?

I would haved liked to understand why or how.

**Comment by bbqsrc** [comment]
I would recommend opening a bug against the code, not the tool you used to try to build it.

cargo ndk is just a thin wrapper around cargo.
