### ISSUE TITLE
Feature request: Printing environment variables set

### ISSUE THREAD

**Issue by torokati44** [bbqsrc/cargo-ndk#128]
First of all, thanks a lot for this tool, it has helped us a lot! ^^

One problem we are facing though, is that sometimes, tools such as `rust-analyzer` also require the whole toolchain to be available to work properly. And `cargo-ndk` is the tool that figures out the environment for the toolchain to be available.

I think it would be neat if `cargo-ndk` had an option to just print the set of environment variables that it would set for `cargo`, instead of launching it - this output could be then (only after careful inspection, of course) sourced into one's shell before using said development tools.

See for reference: https://github.com/ruffle-rs/ruffle-android/commit/ddf2cd670d17ef892ad7ce45e84f611e90853a98

What do you think?

**Comment by bbqsrc** [comment]
Add `-vv` to the build command and it prints it. 😄

**Comment by bbqsrc** [comment]
Got bored, added an `ndk-env` command. (I'm on a bus somewhere between Helsingborg and Göteborg in Sweden right now. Very sunny. Nice view of large expanses of green farmland. 😄)

Let's see if CI likes it.

**Comment by bbqsrc** [comment]
Will publish as 3.5.0 momentarily.

Commit message:
![IMG_7243](https://github.com/bbqsrc/cargo-ndk/assets/279099/373af9f3-71c5-4163-883a-06861c9e5219)

**Comment by bbqsrc** [comment]
So feel free to test it out and let me know if anything is funky.

**Comment by torokati44** [comment]
Thanks a lot, you're awesome!
I can only test a couple hours from now when I get home.
Nice views indeed! :heart_eyes:
_Ha en trevlig resa_, at least according to Google Translate...

**Comment by bbqsrc** [comment]
haha, nagyon szépen köszönjük :D

**Comment by torokati44** [comment]
Uh-oh...:

```
[attila:~/projects/ruffle-android]$ $(cargo ndk-env)
bash: export: `AR_aarch64-linux-android="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"': not a valid identifier
bash: export: `CC_aarch64-linux-android="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"': not a valid identifier
bash: export: `CFLAGS_aarch64-linux-android="--target=aarch64-linux-android21"': not a valid identifier
bash: export: `CXXFLAGS_aarch64-linux-android="--target=aarch64-linux-android21"': not a valid identifier
bash: export: `CXX_aarch64-linux-android="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++"': not a valid identifier
bash: export: `RANLIB_aarch64-linux-android="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib"': not a valid identifier
```

:/

Seems like environment variable names can't contain `-`.
https://unix.stackexchange.com/a/23714

After manually replacing `aarch64-linux-android` with `aarch64_linux_android` in all the variable names, it worked fine though!
https://docs.rs/cc/latest/cc/#external-configuration-via-environment-variables

So it could be forced into the env with `env`, but... the underscores version should work just as well. The only risk is that something else already defined the dashed version, overriding these, but I think that should be fairly rare...?

(PS: "köszönjük" implies that there are multiple people doing the thanking - if it's only you, then it should be "köszönöm". Still appreciating the effort! ^^ )

**Comment by bbqsrc** [comment]
Will update it to print underscores. Forgot about that. 

Had to make it top level since the argument passing functionality might have been affected by the introduction of a subcommand since there presently isn’t any (but i thought there had been lol)

**Comment by bbqsrc** [comment]
Fixed in 3.5.1. :)

**Comment by torokati44** [comment]
Very nice, really good, thank you!

One last off-topic sanity-check, if you don't mind: Are `"`s in the values escaped somewhere before being printed here?
Or is [little Bobby Tables](https://xkcd.com/327/) going to come for us?

**Comment by bbqsrc** [comment]
It's all escaped since I'm printing with `{:?}` and that follows the usual escaping rules.

**Comment by torokati44** [comment]
Ah, beautiful! I was wondering where the outer quotes are even added, but of course, there!
That's it for me, it was a pleasure!

**Comment by bbqsrc** [comment]
Haha but I did find a bug.

```
export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="/Users/brendan/.cargo/bin/cargo-ndk-env"
```

That should definitely be cargo-ndk, not cargo-ndk-env :o

**Comment by bbqsrc** [comment]
3.5.2 fixes that, should be good to go now.

**Comment by torokati44** [comment]
Actually, I have something fishy to report back... 🫤

First, proof that in a fresh shell, I can build the `ruffle-android` project just fine using `cargo-ndk`:

```
[attila:~]$ cd projects/ruffle-android
[attila:~/projects/ruffle-android]$ export ANDROID_NDK_HOME=/home/attila/Android/Sdk/ndk/26.1.10909125/
[attila:~/projects/ruffle-android]$ cargo ndk --platform 29 --target arm64-v8a build
    Building arm64-v8a (aarch64-linux-android)
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
```

This is what `cargo-ndk-env` tells me:
```
[attila:~/projects/ruffle-android]$ cargo ndk-env
export AR_AARCH64_LINUX_ANDROID="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
export CARGO_NDK_SYSROOT_LIBS_PATH="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android"
export CARGO_NDK_SYSROOT_PATH="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
export CARGO_NDK_SYSROOT_TARGET="aarch64-linux-android"
export CARGO_TARGET_AARCH64_LINUX_ANDROID_AR="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="/home/attila/.cargo/bin/cargo-ndk"
export CC_AARCH64_LINUX_ANDROID="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
export CFLAGS_AARCH64_LINUX_ANDROID="--target=aarch64-linux-android21"
export CXXFLAGS_AARCH64_LINUX_ANDROID="--target=aarch64-linux-android21"
export CXX_AARCH64_LINUX_ANDROID="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++"
export RANLIB_AARCH64_LINUX_ANDROID="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib"
export _CARGO_NDK_LINK_CLANG="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
export _CARGO_NDK_LINK_TARGET="--target=aarch64-linux-android21"
```

Copying and pasting the result into this shell to set them as variables:
```
[attila:~/projects/ruffle-android]$ export AR_AARCH64_LINUX_ANDROID="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
export CARGO_NDK_SYSROOT_LIBS_PATH="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android"
export CARGO_NDK_SYSROOT_PATH="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
export CARGO_NDK_SYSROOT_TARGET="aarch64-linux-android"
export CARGO_TARGET_AARCH64_LINUX_ANDROID_AR="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="/home/attila/.cargo/bin/cargo-ndk"
export CC_AARCH64_LINUX_ANDROID="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
export CFLAGS_AARCH64_LINUX_ANDROID="--target=aarch64-linux-android21"
export CXXFLAGS_AARCH64_LINUX_ANDROID="--target=aarch64-linux-android21"
export CXX_AARCH64_LINUX_ANDROID="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++"
export RANLIB_AARCH64_LINUX_ANDROID="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib"
export _CARGO_NDK_LINK_CLANG="/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
export _CARGO_NDK_LINK_TARGET="--target=aarch64-linux-android21"
```

**Note** that this _removes_ the `"` quoting from around the actual values set into the environment, because ... `bash`...

```
[attila:~/projects/ruffle-android]$ echo $CARGO_NDK_SYSROOT_TARGET
aarch64-linux-android
```

The build is now broken:
```
[attila:~/projects/ruffle-android]$ cargo ndk --platform 29 --target arm64-v8a build
clang-17: error: unsupported option '--platform'
clang-17: error: unsupported option '--target'; did you mean '-target'?
clang-17: error: no such file or directory: 'ndk'
clang-17: error: no such file or directory: '29'
clang-17: error: no such file or directory: 'arm64-v8a'
clang-17: error: no such file or directory: 'build'
clang-17: error: no input files
```

Instead of copy-pasting, now using command output substitution:
```
[attila:~/projects/ruffle-android]$ $(cargo ndk-env)
```

**Note** that this _keeps_ the `"` around the actual values set into the environment, because ... `bash`...

```
[attila:~/projects/ruffle-android]$ echo $CARGO_NDK_SYSROOT_TARGET
"aarch64-linux-android"
```

Doing `` `cargo ndk-env` `` instead results in the same thing.
 
But the build still doesn't work, but now for a different reason...

```
[attila:~/projects/ruffle-android]$ cargo ndk --platform 29 --target arm64-v8a build
cargo-ndk: Failed to spawn "\"/home/attila/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang\"" as linker: No such file or directory (os error 2)
[attila:~/projects/ruffle-android]$ 
```

It doesn't matter which method of putting the environment variables (copy-pasting or `$()`) I do first in the fresh shell, the result is the same after each in both orders.

**Comment by Fancy2209** [comment]
I was noticing this in IntelliJ and Android Studio (using the deprecated rust extension), glad I wasn't just going crazy

**Comment by bbqsrc** [comment]
well that's fun lol

I love escaping strings, it's my favourite thing to do before breakfast

**Comment by bbqsrc** [comment]
Today's lesson: `$(cargo ndk-env)` and just copy and pasting the output lead to two very different interpretations of the same export. I hate shells.

**Comment by torokati44** [comment]
It was new for me too yesterday. I wish this wasn't the case, and it hasn't even occurred to me that it was, but it is what it is...
And I also don't like shells. 🥲

_I did like the views from my bus ride though, just like you!_
<img src="https://github.com/bbqsrc/cargo-ndk/assets/288816/52283bf3-3b79-423f-957a-65a42fa7d516" width="200px" />

**Comment by Fancy2209** [comment]
> Today's lesson: `$(cargo ndk-env)` and just copy and pasting the output lead to two very different interpretations of the same export. I hate shells. (Yes I know you said it did this, but omg)

Weirdly on windows, when setting them manually, both on PowerShell and CMD, the result is the same as `$(cargo ndk-env)`

**Comment by bbqsrc** [comment]
> > Today's lesson: `$(cargo ndk-env)` and just copy and pasting the output lead to two very different interpretations of the same export. I hate shells. (Yes I know you said it did this, but omg)
> 
> Weirdly on windows, when setting them manually, both on PowerShell and CMD, the result is the same as `$(cargo ndk-env)`

Yeah this very much doesn't even take into account the existence of Windows. The only sane was to do that would be to output a powershell script.

**Comment by bbqsrc** [comment]
@torokati44 do: `source <(cargo ndk-env)`

**Comment by bbqsrc** [comment]
> > Today's lesson: `$(cargo ndk-env)` and just copy and pasting the output lead to two very different interpretations of the same export. I hate shells. (Yes I know you said it did this, but omg)
> 
> Weirdly on windows, when setting them manually, both on PowerShell and CMD, the result is the same as `$(cargo ndk-env)`

Add `--powershell` to the command to get powershell-compatible output in 3.5.3. 😄

**Comment by torokati44** [comment]
@bbqsrc
> @torokati44 do: source <(cargo ndk-env)

Same result as with simple copy-pasting...

I think `cargo ndk` itself gets confused by all the envvars already being preset using `cargo ndk-env`? :thinking:

**Comment by bbqsrc** [comment]
You shouldn’t do it before using the ndk command, since it is very much just spitting out what ndk is doing on its own. You’d have to run cargo directly and specify the correct target. On 13 Apr 2024, at 12:59, TÖRÖK Attila ***@***.***> wrote:﻿
@bbqsrc

@torokati44 do: source <(cargo ndk-env)

Same result as with simple copy-pasting...
I think cargo ndk itself gets confused by all the envvars already being preset using cargo ndk-env? 🤔

**Comment by torokati44** [comment]
> You shouldn’t do it before using the ndk command, since it is very much just spitting out what ndk is doing on its own. 

Well, okay, sure, but it'd still be nice if it didn't "break itself".
As in, having the environment already set up the way it's intending to set it up _feels like_ it should basically turn the environment setup part of `cargo ndk` into a no-op, but still function exactly as if the environment wasn't set up beforehand...? :thinking: 

> You’d have to run cargo directly and specify the correct target.

Okay, but the issue with this is that it breaks the following workflow:

 - Open a shell
 - Set it up using `. <(cargo ndk-env --target ... --platform ...)`
 - Open an IDE using `rust-analyzer` from that shell, such as VS Code
 - In the built-in terminal of that IDE, issue `./gradlew assembleRelease`
   - This Gradle plugin invokes `cargo-ndk` as one of the build steps: https://github.com/willir/cargo-ndk-android-gradle

**Comment by bbqsrc** [comment]
This is just the nature of environment pollution. Rust analyzer’s config allows specifying env as a JSON blob, that is the recommended way of making it behave.As for the gradle case, don’t set the environment and let ndk do it lolBecause bash can’t support the dashed versions of the env vars, it’s ultimately going to be a best effort to map to all the various pieces of the ecosystem (cc, cmake, etc) to get things running perfectly.As for why the ndk breaks itself, it’s probably the underscored env vars shouldn’t actually be set. Try removing those. On 13 Apr 2024, at 14:13, TÖRÖK Attila ***@***.***> wrote:﻿

You shouldn’t do it before using the ndk command, since it is very much just spitting out what ndk is doing on its own.

Well, okay, sure, but it'd still be nice if it didn't "break itself".
As in, having the environment already set up the way it's intending to set it up feels like it should basically turn the environment setup part of cargo ndk into a no-op, but still function exactly as if the environment wasn't set up beforehand...? 🤔

You’d have to run cargo directly and specify the correct target.

Okay, but the issue with this is that it breaks the following workflow:

Open a shell
Set it up using . <(cargo ndk-env --target ... --platform ...)
Open an IDE using rust-analyzer from that shell, such as VS Code
In the built-in terminal of that IDE, issue ./gradlew assembleRelease

This Gradle plugin invokes cargo-ndk as one of the build steps: https://github.com/willir/cargo-ndk-android-gradle

**Comment by torokati44** [comment]
> Rust analyzer’s config allows specifying env as a JSON blob, that is the recommended way of making it behave.

Oh, right, you're absolutely right! ^^ This is The Way then.

> As for why the ndk breaks itself, it’s probably the underscored env vars shouldn’t actually be set. Try removing those.

Well then this won't be an issue either... :)

Thank you yet again for the thorough support, have a nice weekend!

**Comment by bbqsrc** [comment]
3.5.4 should have the expected behaviour by not putting out the underscore prefixed ones.
