### ISSUE TITLE
What's the difference when handle libc++_shared.so

### ISSUE THREAD

**Issue by cxg666** [bbqsrc/cargo-ndk#132]
1.     #[cfg_attr(target_os = "android", link(name = "c++_shared"))]
       extern "C" {}

2.  ```println!("cargo:rustc-link-lib=c++_shared");```

I canot figure out what's the difference when link c++_shared, but the 2 doesn't really link the shared so.... while 1 works.

**Comment by bbqsrc** [comment]
https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib
