### ISSUE TITLE
Failed loading manifest

### ISSUE THREAD

**Issue by fenhl** [bbqsrc/cargo-ndk#137]
I have a package `night-uniffi` that's part of a [virtual workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-workspace). With `cargo-ndk` 3.5.4, everything works fine. With `cargo-ndk` 3.5.6, the command `cargo ndk --platform=34 --target=arm64-v8a build --package=night-uniffi --lib` errors with the following output:

```
error: Failed loading manifest
error: Could not derive library name from Cargo.toml
```

**Comment by MarijnS95** [comment]
Could also be fallout like https://github.com/bbqsrc/cargo-ndk/pull/135#discussion_r1606097922? Looks like workspaces weren't tested recently.

**Comment by bbqsrc** [comment]
It is likely that. Won't have time to look into this for a while unfortunately, so contributions here are welcomed.

**Comment by ianthetechie** [comment]
Hmm, that's unfortunate. I hit this in a CI pipeline as well which pulled the latest patch release. I use virtual workspaces across several projects, and this thread has been helpful understanding the issue. As for solutions, let's see if I can get my head around the factors.

First, it looks like the changes introduced are aimed at avoiding copying extra libraries which are unneeded/harmful. It tries to do so by looking at `Cargo.toml`.

> As far as I can tell, every rust crate can have 0 or 1 libraries, and package.name is required in Cargo.toml so we always have a name

@mightyguava wrote the above, and it's mostly correct. Every rust _package_ can have 0 or 1 libraries, per [the cargo book](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#library). However, the code as-is assumes that we are parsing a manifest for a single package rather than a workspace, which may contain multiple packages.

I'm not sure that the current model's assumptions hold for more complex projects. In the simple case, there is only one library, so you just recursively parse the workspace member manifests and then get the library/package name. That would work for my use case, but I feel there's something missing for the general case.

Thoughts?

**Comment by mightyguava** [comment]
How are you invoking `cargo-ndk`? We also use workspaces, but our build scripts invoke the build for a single package at a time with the `--package` flag.

We never run the build at the workspace level. Does that automatically build all packages in the workspace? If so, then maybe cargo-ndk may want to revert to the old behavior of copying the whole target directory on build... or probably better, parse all member manifests and copy every lib found.

**Comment by MarijnS95** [comment]
@mightyguava see https://doc.rust-lang.org/cargo/reference/workspaces.html#the-default-members-field. Afaik this defaults to the root `[package]` if the root `Cargo.toml` defines one, and no `default-members` are declared.

**Comment by ianthetechie** [comment]
> How are you invoking `cargo-ndk`? We also use workspaces, but our build scripts invoke the build for a single package at a time with the `--package` flag.

My use case is perhaps similar to @fenhl's as I'm using UniFFI. While there is more than one way to do it, I found that it's easiest to use a [gradle plugin](https://github.com/willir/cargo-ndk-android-gradle). Here is [my invocation](https://github.com/stadiamaps/ferrostar/blob/f2566087fd24475bf820ae89dabfbc44c5263025/android/core/build.gradle#L65).

> We never run the build at the workspace level. Does that automatically build all packages in the workspace? If so, then maybe cargo-ndk may want to revert to the old behavior of copying the whole target directory on build in this scenario... or probably better, parse all member manifests and copy every lib found.

@MarijnS95's answer is correct. However, you raise an interesting idea in the first half of your comment. It looks like the gradle plugin lets you pass arbitrary cargo args. It looks like I can pass `extraCargoBuildArguments = ["-p", "ferrostar"]` to fix it!

I don't know if this will work if you need to bundle multiple libraries, but it works for my use case.

**Comment by bbqsrc** [comment]
I have yanked 3.5.5 and 3.5.6. This'll have to be revisited in 3.6.x or later.

**Comment by dignifiedquire** [comment]
why is this closed? this still happens  for us on `3.5.7`

**Comment by bbqsrc** [comment]
Ah shit, yeah the offending changes were never reverted. I'll yank this too lol

**Comment by mxinden** [comment]
First off, thank you for this excellent crate!

> why is this closed? this still happens for us on `3.5.7`

Same on `quinn` CI:

`cargo-ndk` `v0.3.7` fails with:

```
error: Failed loading manifest
error: Could not derive library name from Cargo.toml
```

See commit: https://github.com/quinn-rs/quinn/commit/7b74ffe2a0f0de47bb112f5009418ac748ab6a94

See GitHub Action run: https://github.com/quinn-rs/quinn/actions/runs/10450996767/job/28936466966

`cargo-ndk` `v0.3.4` succeeds:

See commit: https://github.com/quinn-rs/quinn/commit/898cba1bd709a1582e24a01108c4fc11fcc5259e

See GitHub Action run: https://github.com/quinn-rs/quinn/actions/runs/10451996839/job/28939531590?pr=1950

Discovered on https://github.com/quinn-rs/quinn/pull/1950.

**Comment by bbqsrc** [comment]
It is yanked!

**Comment by bbqsrc** [comment]
@mxinden @dignifiedquire could you try with the `main` branch and let me know if the current state of things works for you?

**Comment by mxinden** [comment]
@bbqsrc `main` branch works:

- [commit](https://github.com/mxinden/quinn/commit/4970052235b0e1c77bc4d2ca43d50a66f6ef8d3c)
- [x86-64 action run](https://github.com/mxinden/quinn/actions/runs/10503348672/job/29096540137)
- [i686 action run](https://github.com/mxinden/quinn/actions/runs/10503348672/job/29096540629)

(There is an unrelated issue with the emulator.)
