### ISSUE TITLE
CARGO_NDK_OUTPUT_PATH is not absolutized

### ISSUE THREAD

**Issue by SamRodri** [bbqsrc/cargo-ndk#139]
If I call `cargo ndk` at the workspace root with a relative `--output-dir`, a crate build script not also on the root will resolve an incorrect path. I think `cargo build` changes the working dir to the manifest dir.

```console
cargo ndk --manifest-path "crates/foo/Cargo.toml" --output-dir "target/build-ndk build
```

**Comment by bbqsrc** [comment]
pull request your way to great success!

**Comment by SamRodri** [comment]
Ok. I will work on this and the panic issue this weekend.

**Comment by bbqsrc** [comment]
Looking forward to reviewing your PR :D
