### ISSUE TITLE
Build broken after v2 update

### ISSUE THREAD

**Issue by kar** [bbqsrc/cargo-ndk#14]
Hi, so I adapted my build invocation to cargo ndk v2, but now I'm getting this error:

```
error: failed to run custom build command for `backtrace-sys v0.1.35`

Caused by:
  process didn't exit successfully: `target/release/build/backtrace-sys-592314409b0beb5b/build-script-build` (exit code: 1)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-linux-android")
  HOST = Some("x86_64-apple-darwin")
  CC_aarch64-linux-android = Some("toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang")
  CFLAGS_aarch64-linux-android = None
  CFLAGS_aarch64_linux_android = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  running: "toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-Wall" "-Wextra" "-E" "src/android-api.c"

  --- stderr


  error occurred: Failed to find tool. Is `aarch64-linux-android21-clang` installed?
```

IIRC, this used to be fixed in older cargo ndk by adding '--lib', but now it seems to not make any difference. Any ideas?

**Comment by bbqsrc** [comment]
I am not certain. Try explicitly declaring the path to your NDK as the env var `ANDROID_NDK_HOME` and see if that helps. 

You can roll back to 1.0 by using cargo install with --vers 1.0.0, if you need to.

**Comment by junhochoi** [comment]
quiche project use cargo-ndk and we have a similar issue after ndk 2.0.0. 
Pinning to 1.0 fixed the issue.

https://github.com/cloudflare/quiche/runs/1681094260?check_suite_focus=true

```
/usr/share/rust/.cargo/bin/cargo ndk --target aarch64-linux-android --android-platform 21 -- build --verbose
[2021-01-11T12:26:13Z ERROR cargo_ndk::cli] invalid argument to option `--target`: Unsupported target: 'aarch64-linux-android'
Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 2
```

**Comment by bbqsrc** [comment]
Your issue is unrelated. Command line arguments have changed. See the readme and --help.

**Comment by junhochoi** [comment]
> Your issue is unrelated. Command line arguments have changed. See the readme and --help.

Oh. The way of specifying architecture trile is changed! I tried and it seems to work -- https://github.com/cloudflare/quiche/pull/809
Thanks! 👍
