### ISSUE TITLE
Why last releases are yanked on crates.io?

### ISSUE THREAD

**Issue by tyranron** [bbqsrc/cargo-ndk#143]
3.5.5, 3.5.6 and 3.5.7 versions are yanked on crates.io. Why the hell?

**Comment by bbqsrc** [comment]
Because I managed to push the same broken code three times. :)

**Comment by kirillzh** [comment]
@bbqsrc any chance you could publish the latest version? We would love to apply one of the fixes in that version for our builds. Thanks!
