### ISSUE TITLE
Target not found [aarch64-linux-android]

### ISSUE THREAD

**Issue by tbraun96** [bbqsrc/cargo-ndk#15]
Using the new mac silicon as the host, I'm trying to ``cargo make`` the repo [here](https://github.com/shekohex/flutterust). Unfortunately, once it gets to the step ``cargo ndk --platform 28 --target aarch64-linux-android build``, I get the following error message:

```
invalid argument to option `--target`: Unsupported target: 'aarch64-linux-android'
```

I have already installed the target via rustup, and it has proven to work in other contexts just fine. However, when in the ``cargo ndk`` context, this error message occurs.

**Comment by bbqsrc** [comment]
Hi @tbraun96. v2 of cargo-ndk changed the target flag to use the more common Android architectures. You can install v1 with `cargo install cargo-ndk --vers 1.0.0`.

However, I would also accept a patch that returns support for the old targets too, it's clearly a mistake to remove the ordinary triples, but I can also support the more natural architectures for Android devs.

**Comment by tbraun96** [comment]
If you could support android (and ios, if that's in the same boat?), that would be wonderful

**Comment by bbqsrc** [comment]
For iOS, use `cargo lipo`. It's linked in the readme.

If you or someone else wants to take a shot at adding support for both the Android-style architectures (ie, `x86`) as well as in its triple form (ie, `aarch64-linux-android`), it's reasonably straightforward to do. Just follow the code for the `--target` flag, find the string matching and add the other targets back. :smile:
