### ISSUE TITLE
macos-15 image got linking error: `linking with `/Users/runner/.cargo/bin/cargo-ndk` failed: exit status: 1`

### ISSUE THREAD

**Issue by Wyvern** [bbqsrc/cargo-ndk#152]
When switched to macos-15 image using cargo-ndk got linking error like below:

```
cargo-ndk: Failed to spawn "/Users/runner/Library/Android/sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang" as linker: No such file or directory (os error 2)
```
macos-14 is fine without problems.

**Comment by bbqsrc** [comment]
I assume you mean with the github actions runner by that label, since the report is missing any further context. This is likely some kind of configuration issue unrelated to cargo-ndk.
