### ISSUE TITLE
Slash in environment variables on windows

### ISSUE THREAD

**Issue by SilverMira** [bbqsrc/cargo-ndk#153]
Similar to #84, unable to cross compile crate with openssl dependency to Android on windows.

Provided perl is set up to correctly use MSYS2's binary, we get this when doing `cargo ndk check`
```
  /bin/sh: line 1: C:UsersUserAppDataLocalAndroidSdkndk26.2.11394342toolchainsllvmprebuiltwindows-x86_64binclang: command not found
```

From the cargo logs, it appears `CC_aarch64-linux-android` is set with windows path separators, and openssl just decides to escape the backslashes.

Minimal reproduction
1. On windows, with path including MSYS2 perl
2. `cargo new --lib test`
3. Add `openssl = { version = "0.10.64", features = ["vendored"] }` in Cargo.toml
4. `cargo ndk --target arm64-v8a check`

Manually setting `CC_aarch64-linux-android`, `AR_aarch64-linux-android` `RANLIB_aarch64-linux-android` with `/` path separators allow openssl to build successfully using just `cargo check --target aarch64-linux-android`

**Comment by bbqsrc** [comment]
Did you try to build as per the [example](https://github.com/bbqsrc/cargo-ndk/tree/main/example/openssl)?

**Comment by SilverMira** [comment]
Yes, it does repro with `-p 28`. I can get the path to be half correct if I change `ANDROID_NDK_HOME` to be using `/` rather than `\`, which yields me this error.

```
/bin/sh: line 1: C:/Users/User/AppData/Local/Android/Sdk/ndk/26.2.11394342toolchainsllvmprebuiltwindows-x86_64binclang: No such file or directory
```

The same happens when I try to build from MSYS2 MINGW64 shell

**Comment by bbqsrc** [comment]
Test against `main`, I suspect I just haven't published the changes.

**Comment by SilverMira** [comment]
Thanks! `cargo install --git https://github.com/bbqsrc/cargo-ndk.git cargo-ndk` and running the build in MSYS2 shell worked.
Closing the issue now
