### ISSUE TITLE
Support bin executable artifacts

### ISSUE THREAD

**Issue by vfsfitvnm** [bbqsrc/cargo-ndk#19]
Hi!
This is not really a problem, but here is my use case.

I'd like to ship a Rust executable within my Android application. Unfortunately, from API 29, the only way to make that possible is to put the executable inside the `lib/<abi>` folder, and thus must be named like `lib<...>.so`.
Rust crate names cannot contain dots `.`, so my build process consists in building the project (`example`), and then renaming it to `libexample.so`, and finally move it to the target abi folder.

It would be cool if there was a flag in `cargo-ndk` (let's say `--bin` or `--type <bin|lib>`) which is aware of this, which would prepend `lib` and append `.so` to the artifcact name instead of logging an error.

I guess the implementation would look like this:
First, get the current package (is there a nicer way than the following?);
Then, iterate over the build targets and so on.

```rust
// inside cli::run

let package = metadata.packages.iter().find(|package| package.manifest_path.eq(cargo_manifest)).unwrap();
for build_target in &package.targets {
    let is_shared_lib = build_target.crate_types.contains(&"bin".into());
    println!("Is {} a shared library? {}", build_target.name, is_shared_lib);
    // etc
}
// etc
```

However, I feel like there should be a major refactoring in order to appropriately support this, and I'm not sure if the required effort is worthy. Just my two cents.

**Comment by bbqsrc** [comment]
I feel like this kind of workaround is not suitable for being supported by this tool, as the use case is rather obscure.
