### ISSUE TITLE
Should cargo-ndk work when building c dependencies with cc?

### ISSUE THREAD

**Issue by SergejJurecko** [bbqsrc/cargo-ndk#2]
For instance building: https://github.com/rust-lang/backtrace-rs/

    cargo ndk --target=armv7-linux-androideabi --android-platform 21 -- build
 
produces:

OPT_LEVEL = Some("0")
TARGET = Some("armv7-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
CC_armv7-linux-androideabi = None
CC_armv7_linux_androideabi = None
TARGET_CC = None
CC = None
CFLAGS_armv7-linux-androideabi = None
CFLAGS_armv7_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
running: "arm-linux-androideabi-clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=armv7-linux-androideabi" "-Wall" "-Wextra" "-E" "src/android-api.c"

--- stderr

error occurred: Failed to find tool. Is `arm-linux-androideabi-clang` installed?

**Comment by bbqsrc** [comment]
Hmm, strange. It is meant to work with `cc` projects, as that's one of my primary use cases and we're using `cargo-ndk` for that right now without issue.

I'm sick at the moment so unless I get a burst of energy to look into this, I'll need to take a look next week or someone else can dig a bit.

**Comment by bbqsrc** [comment]
@SergejJurecko I found some energy. Try pointing at the master branch and let me know if it works, as I got backtrace-rs to build locally with the changes I made. :smile:

**Comment by SergejJurecko** [comment]
Yes it works thanks.

**Comment by fdoyon** [comment]
Thanks for this. This is a real lifesaver when dealing with x-compiling.

**Comment by bbqsrc** [comment]
Published v0.4.1 on crates.io.
