### ISSUE TITLE
Stripping fails for ARMv7

### ISSUE THREAD

**Issue by dnaka91** [bbqsrc/cargo-ndk#21]
When I try to run `cargo ndk -t armeabi-v7a -t arm64-v8a -t x86 -t x86_64 -o (pwd)/jniLibs -v build --release` I always get an error at the last strip where cargo ndk tries to strip the binary.

I found out that (at least for MacOS) the binary name is `arm-linux-androideabi-strip` whereas cargo ndk uses the **armv7-linux-androideabi** triple for ARMv7.

Wondering whether this is something MacOS specific or fails on all platforms. I'm currently using NDK version `21.4.7075529` so that might also be something that changed in the NDK over time.

**UPDATE:** I installed the Android SDK with NDK in a clean Docker image to check it out for linux systems. Same situation there.

**Comment by bbqsrc** [comment]
Make sure you have version 2.3.0 of `cargo ndk` and let me know if you can reproduce. I have tested with NDK 22 and have no issues.

**Comment by dnaka91** [comment]
Unfortunately it still fails, but due to another error.
My `ANDROID_NDK_HOME` points to `~/Library/Android/sdk/ndk` which seems correct for most Android tools to find the NDK but messes with the resolution of `cargo-ndk` and it fails to get the right path.

I saw at only for `ANDROID_NDK_HOME` and `NDK_HOME` the resolution just stops here and isn't further processed with `highest_version_ndk_in_path` to find the latest installed NDK subfolder. 
https://github.com/bbqsrc/cargo-ndk/blob/b42bde9cf6315f9c4f73ce15cd0f9c69207acf9f/src/cli.rs#L58-L64

Shouldn't this be processed as well? Maybe it needs a bit extra tweaking for the case of one of these env vars already pointing to the NDK version subfolder.

Also, in Gradle the specific NDK version can be defined as well instead of taking the latest one. Maybe the `package.metadata.ndk` settings could be extended to allow defining a specific NDK version?

If you agree on these points I can prepare the needed PRs for these changes 🙇‍♂️

**Comment by dnaka91** [comment]
To answer your original questions I temporarily adjusted my `ANDROID_NDK_HOME` to point to the right subfolder and it works now. So stripping is working, but still the above mentioned issue exists. I can split it up into a separate issue if you prefer that?

**Comment by bbqsrc** [comment]
@dnaka91 create a new issue for the problems you highlighted, and I'd happily accept PRs solving those issues you raised. 😄

**Comment by dnaka91** [comment]
Sounds good to me 👍
