### ISSUE TITLE
NDK 23 beta: Build fails with `unable to find library -lgcc`

### ISSUE THREAD

**Issue by zskamljic** [bbqsrc/cargo-ndk#22]
I'm trying to build a new project, however when running the command `cargo ndk -t aarch64-linux-android -o ./jniLibs build --release`, but I end up with an error;

```
error: linking with `/home/<user>/Android/Sdk/ndk/23.0.7421159/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang` failed: exit status: 1
  |
  = note: ld: error: unable to find library -lgcc
          clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by bbqsrc** [comment]
Does it work if you use ndk 22.x or lower?

**Comment by zskamljic** [comment]
Yes, it seems that way the .so file is created

**Comment by bbqsrc** [comment]
So, NDK 23 removes libgcc entirely. Rust relies on this for providing missing builtins on Android.

https://github.com/rust-lang/rust/pull/85806 should fix it.

**Comment by bbqsrc** [comment]
This seems to still only work with nightly. To use aarch64 builds as an example, this will work:

```
cargo +nightly ndk -t arm64-v8a build -Zbuild-std
```

The problem seems to be the Rust CI builds for Android still use an older NDK or something similar that causes it to require libgcc. If you build your own std, no problem.

**Comment by tux3** [comment]
The target-specific `ar`, `strip`, and other tools except clang/clang++ also appear to have been removed in NDK 23.

For example cargo-ndk expects:
```
[2021-09-09T19:30:58Z DEBUG cargo_ndk::cargo] ar: /opt/android/ndk/23.0.7599858/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-ar
```
But `i686-linux-android-ar` does not exist in NDK 23, only `llvm-ar`.

Same with strip (the first error I get is `thread 'main' panicked at 'strip crashed: Os { code: 2, kind: NotFound, message: "No such file or directory" }'`)

**Comment by bbqsrc** [comment]
@tux3 this is a separate issue, please create one and report this there :smile:

**Comment by acrrd** [comment]
Do you think that porting this workaround will be suitable for cargo ndk? 
https://github.com/rust-windowing/android-ndk-rs/blob/f24606cc840af2f97f0daebe1e2e7cd3aca52287/cargo-apk/src/apk.rs#L184

**Comment by bbqsrc** [comment]
If somebody wishes to do so.

**Comment by Fernthedev** [comment]
I'd like to mention that the workaround named above (building with std) does not work in my situation. I am using NDK R24 if that requires mentioning
I still get `ld: error: unable to find library -lgcc` using this command invocation:
```
rustup target install aarch64-linux-android
rustup component add rust-src --toolchain nightly --target aarch64-linux-android
cargo +nightly ndk -t arm64-v8a -o target/release build -Zbuild-std --verbose --release
```
If anyone would like to test this very specific scenario, the project is over [here](https://github.com/Fernthedev/songdatacore_rust) and shouldn't require extensive setup configurations.

Note:
- I have not tested with other NDK versions
- I have not tested other rust projects

Am I missing something? Feel free to call me out on it

**Comment by Qinruiy** [comment]
> I'd like to mention that the workaround named above (building with std) does not work in my situation. I am using NDK R24 if that requires mentioning I still get `ld: error: unable to find library -lgcc` using this command invocation:
> 
> ```
> rustup target install aarch64-linux-android
> rustup component add rust-src --toolchain nightly --target aarch64-linux-android
> cargo +nightly ndk -t arm64-v8a -o target/release build -Zbuild-std --verbose --release
> ```
> 
> If anyone would like to test this very specific scenario, the project is over [here](https://github.com/Fernthedev/songdatacore_rust) and shouldn't require extensive setup configurations.
> 
> Note:
> 
> * I have not tested with other NDK versions
> * I have not tested other rust projects
> 
> Am I missing something? Feel free to call me out on it
> 
> Update: Tested NDK R23c and still does not work

https://github.com/rust-lang/rust/pull/85806#issuecomment-1096266946

create 4 text files named libgcc.a in the same folders with this contents
it works on ndk 24.0.8215888

**Comment by rib** [comment]
> Do you think that porting this workaround will be suitable for cargo ndk? https://github.com/rust-windowing/android-ndk-rs/blob/f24606cc840af2f97f0daebe1e2e7cd3aca52287/cargo-apk/src/apk.rs#L184

For reference the PR https://github.com/bbqsrc/cargo-ndk/pull/67 I recently opened effectively supports this same workaround.
