### ISSUE TITLE
Feature Request: copy built so files to src/main/jniLibs

### ISSUE THREAD

**Issue by igrep** [bbqsrc/cargo-ndk#3]
I wish `cargo ndk` command had a feature to copy the built `.so` files to the default load path of an Android project (`src/main/jniLibs/<arch_name>`) after building.
This feature would make it a "one-stop plugin for people writing Android libraries in Rust"!

One problem to solve is the CLI:

- Add an option to `cargo ndk build`? Or a new subcommand such as `cargo ndk install`?
- How to specify the path to Android project directory? There can be several directory structures for such projects (one with several "app" directories, one whose "app" directory and Rust project directory are separate, etc.)

After I made arrangements for those problems with you, I'll implement it.

**Comment by bbqsrc** [comment]
You could add a `-o` flag with a full path to a `jniLibs` directory, and then have the script drop the `.so` files into the correctly named targets.

If the `-o` flag is optional, then it doesn't break anything and just does a final step after the build completes. :smile:

**Comment by igrep** [comment]
Thank you!
But I got a new idea: Creating `cargo-install-dynlibs`, which is `cargo install` for dynlibs, would solve the problem!
I guess combining `cargo-install-dynlibs` with `cargo-ndk` is equivalent to the `-o` option you suggested.

**Comment by igrep** [comment]
Fortunately, the nightly version of cargo has already the feature I want: `cargo build`'s `--out-dir` option.
This is exactly what I want. So `-o` option wouldn't be necessary.
I'll close. Thanks!
