### ISSUE TITLE
NDK 23 missing *-ar tools

### ISSUE THREAD

**Issue by JJChill** [bbqsrc/cargo-ndk#38]
I'm getting the following error because NDK 23 doesn't seem to have the *-ar tools available. Using NDK 22 is fine.

`error occurred: Failed to find tool. Is /Users/<user>/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar installed?`

**Comment by jmesmon** [comment]
It looks like it's location moved to `..../ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar` or similar. Should be possible to tweak things to pick `llvm-ar` if it exists.

**Comment by bbqsrc** [comment]
Fixed in March.
