### ISSUE TITLE
support env vars for NDK location that match cmake's support

### ISSUE THREAD

**Issue by jmesmon** [bbqsrc/cargo-ndk#39]
[cmake](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-android) uses `ANDROID_NDK` and `ANDROID_NDK_ROOT` env variables to locate the ndk. `cargo-ndk` instead uses `ANDROID_NDK_HOME` and `NDK_HOME`.

It would be good to support the env vars used by cmake to reduce confusion.

**Comment by rib** [comment]
I hadn't seen this issue to mention it in my PR but it looks like this is fixed by https://github.com/bbqsrc/cargo-ndk/pull/68
