### ISSUE TITLE
shared library file  has no soname field

### ISSUE THREAD

**Issue by ag2s20150909** [bbqsrc/cargo-ndk#58]
shared library file  has no ```soname``` field

https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_NO_SONAME.html
```
add_library(lib_xxx SHARED IMPORTED)
set_target_properties(lib_xxx PROPERTIES IMPORTED_LOCATION
        /path_to_lib/libxxx.so)
set_property(TARGET lib_xxx PROPERTY IMPORTED_NO_SONAME 1)
```

https://github.com/bbqsrc/cargo-ndk/pull/43#issue-1093192375

**Comment by bbqsrc** [comment]
This, so far as I can tell, has nothing to do with cargo-ndk.
