### ISSUE TITLE
Setup C/C++ toolchain

### ISSUE THREAD

**Issue by katyo** [bbqsrc/cargo-ndk#6]
In order to deal with some crates, like bindings, it is important to provide C/C++ toolchain for building target code.
For reference, how _cargo apk_ does it:
https://github.com/rust-windowing/android-rs-glue/blob/505330693a3ec1e012595b0ad4c2d1e3be411414/cargo-apk/src/ops/build/compile.rs#L50-L52

**Comment by bbqsrc** [comment]
I'd be happy to accept a patch that implements this. 😄

**Comment by bbqsrc** [comment]
I'm considering this stale. If there's any issues, open a new issue.
