### ISSUE TITLE
[BUG] `--bindgen` flag has misleading behavior

### ISSUE THREAD

**Issue by ebraraktas** [bbqsrc/cargo-ndk#71]
I was using `cargo-ndk` with custom `BINDGEN_EXTRA_CLANG_ARGS` enviroment variable for so long, but it seems that new versions `cargo-ndk` overwrites that environment variable whether you pass `--bindgen` or omit it. 

In my opinion, [this commit](https://github.com/bbqsrc/cargo-ndk/pull/62/commits/e8b6e6153c4429f1cee4488062c47d0b2f8be9c6) in [this PR](https://github.com/bbqsrc/cargo-ndk/pull/62/) must be reverted (in other words, `else` block must be deleted). `--bindgen` flag must be an **opt-in** flag and it mustn't change behavior if you omit it.

I can create a PR for this if you like.

**Comment by bbqsrc** [comment]
Fixed in v2.11.0.
