### ISSUE TITLE
Provide workaround for crates that uses bindgen

### ISSUE THREAD

**Issue by vimmerru** [bbqsrc/cargo-ndk#8]
A lot of crates use https://github.com/rust-lang/rust-bindgen to create bindings for C structures. The problem is current versions of bindgen don't provide correct target for invoked clang during cross-compilation. As a result ```cargo-ndk``` can't compile such crates.

Here is workaround to set BINDGEN_EXTRA_CLANG_ARGS variable and provide target here. For example, BINDGEN_EXTRA_CLANG_ARGS="--target=aarch64-linux-android"

It would be nice if this workaround be applied by ```cargo-ndk```

**Comment by bbqsrc** [comment]
I'd happily accept a pull request adding a default that applied these env vars, with a flag for disabling them like `--no-bindgen-env`.

**Comment by bbqsrc** [comment]
I'm considering this issue stale. If someone in the future wishes to reopen this, open a new issue.
