### ISSUE TITLE
Cargo.lock is missing

### ISSUE THREAD

**Issue by orhun** [bbqsrc/cargo-ndk#82]
Hello!

Cargo.lock should be present in the repository due to `cargo-ndk` being a "bin" project, however it is ignored via `.gitignore`.

This is also important for [reproducible builds](https://wiki.archlinux.org/title/Rust_package_guidelines#Prepare) since `--locked` flag fails when `Cargo.lock` is not found.

I propose committing `Cargo.lock` to the repository and removing it from `.gitignore`. Happy to submit a PR :)

**Comment by bbqsrc** [comment]
Fixed and published as v2.12.3. :)

**Comment by orhun** [comment]
Cool, thanks!
