### ISSUE TITLE
Only invoke cargo metadata for desired target(s)

### ISSUE THREAD

**Issue by jonhoo** [bbqsrc/cargo-ndk#83]
Unlike most other cargo tools, `cargo metadata` counter-intuitively defaults to including _all_ targets. This means that with the current logic, `cargo-ndk` ends up processing (and thus downloading dependencies for) _all_ targets even though the user has specifically called out the targets they want to build for. Specifically, in the `MetadataCommand` invocation here

https://github.com/bbqsrc/cargo-ndk/blob/d8f373a04ea2d30e854542487ea95fb162dcafb7/src/cli.rs#L235

`cargo-ndk` should probably always specify [`--filter-platform`](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html#output-options) to each of the specified targets via [`MetadataCommand::other_options`](https://docs.rs/cargo_metadata/0.15.2/cargo_metadata/struct.MetadataCommand.html#method.other_options). Unfortunately `--filter-platform` only takes a single target triple, so you'd have to run metadata once per platform, but that's probably what you'd want to do anyway, since the dependency closure _can_ vary between platforms.

Alternatively, if you aren't using any of the dependency metadata info, and are just invoking `cargo metadata` in order to get information about the workspace, you can call [`MetadataCommand::no_deps`](https://docs.rs/cargo_metadata/0.15.2/cargo_metadata/struct.MetadataCommand.html#method.no_deps), which also makes the `cargo metadata` invocation a fair bit faster!

**Comment by bbqsrc** [comment]
Hey @jonhoo,

Actually planning on reworking the metadata handling and may entirely remove it in v3.

**Comment by bbqsrc** [comment]
Done. :)
