### ISSUE TITLE
Wrong tag

### ISSUE THREAD

**Issue by orhun** [bbqsrc/cargo-ndk#86]
Hello!

I realized `v2.15.5` was tagged today. However, it should be `v2.12.5` instead. I just wanted to let you know.

You can fix this by running:

```sh
git fetch --tags
git tag -d v2.15.5
git push --delete origin v2.15.5
git tag v2.12.5 0f6487b93a54d92603b56ea85d613009ed76b6e2
git push --tags
```

**Comment by bbqsrc** [comment]
lol, god, thanks so much.
