### ISSUE TITLE
Copy all .so files instead of the ones just generated.

### ISSUE THREAD

**Issue by ganfra** [bbqsrc/cargo-ndk#89]
We have multiple ffi modules in our project we compile for different gradle modules.
This code https://github.com/bbqsrc/cargo-ndk/blob/8478e58c712c773e4be6df9978dba92bd877f400/src/cli.rs#L386-L396
is copying all the .so files in the target directories. We end up having `so` files from previous build because of that.
The copy method should just target the files we generated from the build instead.

**Comment by bbqsrc** [comment]
Happy to accept a pull request that does so 😄
