### ISSUE TITLE
"No archive symbol table" Linker error

### ISSUE THREAD

**Issue by i-schuetz** [bbqsrc/cargo-ndk#9]
I ran:
```
cargo ndk --platform 29 --target x86_64-linux-android build
```

And got this:

```
error: linking with `/Users/username/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android29-clang` failed: exit code: 1
...

  = note: /Users/username/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: ssl: no archive symbol table (run ranlib)
          /Users/username/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: crypto: no archive symbol table (run ranlib)
          clang: error: linker command failed with exit code 1 (use -v to see invocation)         
```
What is the problem?

My `$NDK_HOME`:
`/Users/username/Library/Android/sdk/ndk/21.3.6528147/`

**Comment by i-schuetz** [comment]
Was able to reproduce it with NDK 20.0.5594570 too.

**Comment by bbqsrc** [comment]
What happens if you use `--platform 21`?

**Comment by i-schuetz** [comment]
Same error.

**Comment by bbqsrc** [comment]
What version is your `cargo ndk`?

**Comment by i-schuetz** [comment]
1.0.0

**Comment by bbqsrc** [comment]
Okay, then my next guess is that it has something to do with the particular dependencies of your project.

If you're using something like `reqwest` or similar, see if you can't use `rustls` or use a vendored openssl as part of the features.

If you have a repository that reproduces the issue, that would be helpful. :smile:

**Comment by i-schuetz** [comment]
I'm using reqwest. I had initially some open ssl errors, but fixed them by installing openssl with brew and adding an `OPENSSL_DIR` env variable with the path.

This is the project (with the android integration branch):
https://github.com/Co-Epi/app-backend-rust/tree/feature/android

**Comment by bbqsrc** [comment]
That won't work because those openssl dylibs are for your macOS computer and not for Android, so linking will not work.

Try disabling default features and enabling `rustls-tls` as described here: 
https://docs.rs/reqwest/0.10.6/reqwest/#optional-features

**Comment by i-schuetz** [comment]
Nice, that fixed it!
```
[dependencies.reqwest]
default-features = false
version = "0.10.2"
features = ["blocking", "json", "rustls-tls"]
```
Out of curiosity, do you know why it worked with `aarch64-linux-android`?

**Comment by bbqsrc** [comment]
The NDK is a very strange beast. It is possible that the toolchain for aarch64 includes openssl but the older 32bit toolchain does not. There's a lot of oddities in the NDK.

**Comment by i-schuetz** [comment]
Thanks!

**Comment by i-schuetz** [comment]
(Especially for the quick replies 🙂)

**Comment by bbqsrc** [comment]
You're welcome. :smile:
