### ISSUE TITLE
Fail to compile openssl

### ISSUE THREAD

**Issue by Ylarod** [bbqsrc/cargo-ndk#90]
RANLIB is not automatically set by `cargo ndk`.

This issue can be fixed by manually setting RANLIB to /path/to/llvm-ranlib

[log.txt](https://github.com/bbqsrc/cargo-ndk/files/10855385/log.txt)

**Comment by bbqsrc** [comment]
Added in https://github.com/bbqsrc/cargo-ndk/commit/0640e91d55cf7076fe5b2c907188f971ba7a9c28.

Can you test and let me know if this works for you?

**Comment by Ylarod** [comment]
This works fine for me, thanks !
