### ISSUE TITLE
Error copying targets when using profile dev

### ISSUE THREAD

**Issue by ganfra** [bbqsrc/cargo-ndk#93]
When using profile dev like so `cargo ndk build --profile dev`

It seems that the target directory created is called `debug` and not `dev` but cargo-ndk looks for `dev` directory  :
 
`[2023-03-22T15:55:18Z ERROR cargo_ndk::cli] No such file or directory (os error 2) "rust-repository/target/aarch64-linux-android/dev"`

**Comment by ganfra** [comment]
Yes all good! I'd appreciate a release with the fix :-)

**Comment by ganfra** [comment]
Hi! Any updates on a potential release ? :-)

**Comment by bbqsrc** [comment]
sometimes

**Comment by bbqsrc** [comment]
Published. 😄

**Comment by ganfra** [comment]
Thanks, appreciate it :-)
